C $$$$$$
C       SUBROUTINE CODIFF(DELTS,HRU,HV,IMIN,IMAX,LC,LCZ,M,RMID,COD,COD2)  ! KC 2025-05-31
      SUBROUTINE CODIFF(HRU,M,RMID,COD,COD2)

C 2/91 SUBROUTINE ALTERED TO ALLOW DIFFERENT FC'S FOR DIFFERENT
C      MECHANISMS (COMMON BLOCK VMULT2)

      PARAMETER (JSON=5000)
      IMPLICIT REAL*8(A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
      COMMON/CONST1/ CLN,CLNI,C4PI,C4PIL,C4PI3L,CC13,CC23,CPI
      COMMON/INTVAR/ALM(JSON),DELAMI(JSON),DELMI(JSON),DM(JSON),
     *     EPSILM(JSON),HGM(JSON),HS3(JSON),PM(JSON),
     *     QDTMI(JSON),RM(JSON),TM(JSON)
      ! old version: COMMON/INTVR2/AMUM(JSON),THDIFM(JSON),VISCM(JSON),WM(JSON)
      !COMMON/INTVR2/AMUMI(JSON),THDIFMI(JSON),VISCMI(JSON),WM(JSON)
      COMMON/MDPHY/AMUM(JSON),CPM(JSON),DELM(JSON),DELAM(JSON),
     *             DELRM(JSON),ESUMM(JSON),OM(JSON),QDTM(JSON),
     *             THDIFM(JSON),VELM(JSON),VISCM(JSON),EPSM(JSON)
      COMMON/TEMP2/VES(JSON),VES0(JSON),VSS(JSON),VSS0(JSON),
     *     HLE(JSON),VGSF(JSON),VGSF0(JSON),VMU(JSON)
      COMMON/VMULT/FW,FC,FO,FES,FGSF,FMU,FSS,RCRIT
      COMMON/VMULT2/FESC,FSSC,FGSFC,IES,IGSF,IMU
      COMMON/ADVEC/FADV(JSON),FADV0(JSON)
      COMMON/VARFC/VFC(JSON),LVFC,LDIFAD
C MHP 9/93
      COMMON/NOTRAN/LNOJ
C       DIMENSION HRU(JSON),HV(JSON),COD(JSON),LC(JSON),LCZ(JSON),  ! KC 2025-05-31
      DIMENSION HRU(JSON),COD(JSON),RMID(JSON),COD2(JSON)
C MHP 02/12 PERMIT CONSTANT DIFFUSION COEFFICIENT
C KC 2025-05-30 reordered common block elements
C       COMMON/MAG/LCODM,CODM
      COMMON/MAG/CODM,LCODM
      SAVE

C  THIS SR DETERMINES THE RUN OF CHARACTERISTIC VELOCITY LENGTH
C  SCALES FOR THE DIFFUSION EQUATIONS.
C
C  INPUT VARIABLES
C
C       DECLARED:
C  HRU : RUN OF RADIUS (UNLOGGED) OF THE MIDPOINTS OF THE SHELLS.
C  M : NUMBER OF SHELLS.
C  HV : RUN OF CHARACTERISTIC DIFFUSION VELOCITIES.
C  LC : FLAG SET T IF ZONE IS CONVECTIVE.
C  LCZ : FLAG SET T IF ZONE IS CONVECTIVE FOR ANGULAR MOMENTUM
C        TRANSPORT PURPOSES(I.E. INCLUDES OVERSHOOT REGIONS).
C  M : NUMBER OF SHELLS.
C  FC,FO,FW : USER PARAMETERS.  THE DIFFUSION COEFFICIENTS
C  CAN BE MODIFIED BY THESE THREE PARAMETERS.
C  VELM : RUN OF CONVECTIVE VELOCITIES.
C
C  OUTPUT VARIABLES
C
C       DECLARED
C  COD : RUN OF DIFFUSION COEFFICENTS FOR ANGULAR MOMENTUM TRANSPORT.
C  COD2 : SAME, WITH RESPECT TO COMPOSITION TRANSPORT.
C  RMID : RMID(I) IS DEFINED AS THE AVERAGE OF HRU(I) AND HRU(I-1).
C       FROM COMMON BLOCKS:
C       IN COMMON BLOCKS
C  HLE : RUN OF CHARACTERSITIC VELOCITY LENGTH SCALES.
C
C  NOTE ON STORAGE: COD,V, AND HLE ARE CALCULATED AT THE MIDPOINT
C  BETWEEN MASS POINTS. ELEMENT I CONTAINS THE INFORMATION FOR THE
C  (I,I-1) INTERFACE.

      HLE(1) = 0.0D0
      RMID(1) = 0.0D0
      DO I = 2,M
         HLE(I) = 0.0D0
         RMID(I) = 0.5D0*(HRU(I)+HRU(I-1))
      END DO
C MHP 9/14 ADDED LOOP TO ALLOW A CONSTANT BACKGROUND DIFFUSION COEFFICIENT
      CON1 = C4PI*FW
      IF(.NOT.LCODM)THEN
         IF(.NOT.LVFC) THEN
            CON2 = CON1*FC
            DO I = 2,M
               COD(I)=CON1*(VES(I)+VGSF(I)+VSS(I))*RMID(I)
               COD2(I)=CON2*(FESC*VES(I)+FGSFC*VGSF(I)+FSSC*VSS(I))
     *              *RMID(I)
C               HLE(I)=RMID(I)
            END DO
         ELSE
            DO I = 2,M
               COD(I) = CON1*(VES(I)+VGSF(I)+VSS(I))*RMID(I)
               COD2(I) = COD(I)*VFC(I)
C               HLE(I) = RMID(I)
            END DO
         ENDIF
      ELSE
         IF(.NOT.LVFC) THEN
            CON2 = CON1*FC
            DO I = 2,M
               COD(I)=CON1*(CODM+(VES(I)+VGSF(I)+VSS(I))*RMID(I))
               COD2(I)=CON2*(FESC*VES(I)+FGSFC*VGSF(I)+FSSC*VSS(I))
     *                 *RMID(I)
            END DO
         ELSE
            DO I = 2,M
               COD(I) = CON1*(VES(I)+VGSF(I)+VSS(I))*RMID(I)
               COD2(I) = COD(I)*VFC(I)
C MHP 8/13 ADD D.C. AFTER SCALE FACTOR FOR MIXING APPLIED
               COD(I) = COD(I)+CON1*CODM
            END DO
         ENDIF
      ENDIF
C OPTION TO SUPPRESS ANGULAR MOMENTUM TRANSPORT (BUT PERMIT MIXING).
      IF(LNOJ)THEN
         DO I = 2,M
            COD(I) = 0.0D0
         END DO
      ENDIF
      RETURN
      END
