C $$$$$$
      SUBROUTINE CTRIDI(N)

      PARAMETER (JSON=5000)
      IMPLICIT REAL*8 (A-H,O-Z)
      COMMON/TRIDI/A(JSON),B(JSON),C(JSON),D(JSON),U(JSON),GAMA(JSON)
      SAVE

C  SOLVES A TRIDIAGONAL MATRIX SYSTEM FOR THE FRACTIONAL ABUNDANCE
C  OF A SPECIES. NEW ABUNDANCE IS STORED IN ARRAY U.
C  THIS ROUTINE IS FROM NUMERICAL RECIPES, P.40.

      BET = B(1)
      U(1) = D(1)/BET
      DO 1 J=2,N
         GAMA(J) = C(J-1)/BET
         BET = B(J) - A(J)*GAMA(J)
         IF( BET.EQ.0 ) STOP '#TRIDIA:SINGULAR MATRIX'
         U(J) = (D(J) - A(J)*U(J-1))/BET
    1 CONTINUE
      DO 2 J=N-1,1,-1
         U(J) = U(J) - GAMA(J+1)*U(J+1)
    2 CONTINUE

      RETURN
      END
