C $$$$$$
      SUBROUTINE GET_IMP_DIFFCO(ALPHA,ECOD2_H,EX_H,EQCOD2X_H,A,B,C,NPT)

      PARAMETER (JSON=5000)
      IMPLICIT REAL*8(A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
      DIMENSION ALPHA(JSON),ECOD2_H(JSON),EX_H(JSON),EQCOD2X_H(JSON),
     *   A(JSON),B(JSON),C(JSON)
      SAVE

C CORRECT DIFFUSION COEFFICEINTS FOR CHANGE IN X IN THE PREVIOUS ITERATION.
      DO 10 I=1,NPT-1
         ECOD2_H(I)=ECOD2_H(I)+EQCOD2X_H(I)*EX_H(I)
   10 CONTINUE
C NOW RECOMPUTE ELEMENTS OF THE TRIDIAGONAL MATRIX SYSTEM.
      A(1) = 0.0D0
      B(1) = 1.0D0 + ALPHA(1)*ECOD2_H(1)
      C(1) = -ALPHA(1)*ECOD2_H(1)
C   911 FORMAT(5X,I5,1P3E10.2)
      DO 20 I=2,NPT-1
         A(I) = -ALPHA(I)*ECOD2_H(I-1)
         B(I) = 1.0D0 + ALPHA(I)*(ECOD2_H(I-1)+ECOD2_H(I))
         C(I) = -ALPHA(I)*ECOD2_H(I)
   20 CONTINUE
      A(NPT) = -ALPHA(NPT)*ECOD2_H(NPT-1)
      B(NPT) = 1.0D0 + ALPHA(NPT)*ECOD2_H(NPT-1)
      C(NPT) = 0.0D0
      RETURN
      END
