CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     HSUBP
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE HSUBP (HCOMP,HD,HP,HR,HS,HT,JEDGE,PSCAHE)

      PARAMETER (JSON=5000)
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
      COMMON/CONST1/ CLN,CLNI,C4PI,C4PIL,C4PI3L,CC13,CC23,CPI
      COMMON/CONST2/CGAS,CA3,CA3L,CSIG,CSIGL,CGL,CMKH,CMKHN
C DBG 7/92 COMMON BLOCK ADDED TO COMPUTE DEBYE-HUCKEL CORRECTION.
      COMMON/DEBHU/CDH,ETADH0,ETADH1,ZDH(18),XXDH,
     1             YYDH,ZZDH,DHNUE(18),LDH
      DIMENSION HCOMP(15,JSON),HD(JSON),HP(JSON),HR(JSON),HS(JSON),
     *          HT(JSON),FXION(3)
      SAVE

C *** CALCULATES THE LOCAL PRESSURE SCALE HEIGHT AT THE EDGE OF A
C     CONVECTIVE REGION (PD DEC. 1984) 2/91 MHP REVISED FOR YREC/MARK6***
C
C  CALL EQUATION OF STATE TO DETERMINE THE MEAN MOLECULAR WEIGHT.
      LDERIV = .FALSE.
      LATMO = .TRUE.
      KSAHA = 0
      X = HCOMP(1,JEDGE)
      Z = HCOMP(3,JEDGE)
      PL = HP(JEDGE)
      TL = HT(JEDGE)
      DL = HD(JEDGE)
      IF (LDH) THEN
         XXDH = HCOMP(1,JEDGE)
         YYDH = HCOMP(2,JEDGE)+HCOMP(4,JEDGE)
         ZZDH = HCOMP(3,JEDGE)
         ZDH(1) = HCOMP(5,JEDGE)+HCOMP(6,JEDGE)
         ZDH(2) = HCOMP(7,JEDGE)+HCOMP(8,JEDGE)
         ZDH(3) = HCOMP(9,JEDGE)+HCOMP(10,JEDGE)+HCOMP(11,JEDGE)
      END IF
      CALL EQSTAT(TL,T,PL,P,DL,D,X,Z,BETA,BETAI,BETA14,FXION,
     *            RMU,AMU,EMU,ETA,QDT,QDP,QCP,DELA,QDTT,QDTP,
     *            QAT,QAP,QCPT,QCPP,LDERIV,LATMO,KSAHA)
C  COMPUTE PRESSURE SCALE HEIGHT.
      SL = HS(JEDGE)
      RL = HR(JEDGE)
      PSCAP = RMU*EXP(CLN*(TL-CGL-SL+RL+RL))
      PSCAHE = EXP(CLN*(PL + 2.0D0*RL - DL - CGL - SL))
      RETURN
      END
