
C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C   INTER3
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C INTER3
      SUBROUTINE INTER3(A,B,C,X)

      IMPLICIT REAL*8 (A-H,O-Z)
      DIMENSION A(3),B(3),C(3)
      SAVE

C INTER3 IS THE INTERPOLATION ROUTINE FOR DENSITY IN THE LIVERMORE
C OPACITY TABLES, AND IT USES A 3-POINT LAGRANGIAN INTERPOLATION SCHEME.
      A32 = A(3) - A(2)
      A31 = A(3) - A(1)
      A21 = A(2) - A(1)
      D1 = A21*A31
      D2 = -A21*A32
      D3 = A31*A32
      XA1 = X - A(1)
      XA2 = X - A(2)
      XA3 = X - A(3)
      B(1) = (XA2*XA3)/D1
      B(2) = (XA1*XA3)/D2
      B(3) = (XA1*XA2)/D3
      C(1) = (XA2 + XA3)/D1
      C(2) = (XA1 + XA3)/D2
      C(3) = (XA1 + XA2)/D3

      RETURN
      END
