      SUBROUTINE LAX_WENDROF1(DT,ECOD1,EM,NPT,STOT,EX_H,LDOLI)

      PARAMETER (JSON=5000)
      IMPLICIT REAL*8(A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
      COMMON/CONST1/ CLN,CLNI,C4PI,C4PIL,C4PI3L,CC13,CC23,CPI
C MHP 3/94 ADDED METAL DIFFUSION
      COMMON/GRAVS3/FGRY,FGRZ,LTHOUL,LDIFZ
      COMMON/GRAVEZ/ECOD1Z(JSON),ECOD1Z_H(JSON),ECOD2Z_H(JSON),
     *              EQCOD1Z_H(JSON),EQCOD2Z_H(JSON),EZ(JSON),
     *              EZ_H(JSON)
      DIMENSION ECOD1(JSON),EM(JSON),EX_H(JSON)
      SAVE

C VARIABLES : ECOD1 IS RUN OF DIFFUSION COEFFICIENTS, EM IS RUN OF MASSES,
C AND EX_H IS RUN OF CHANGES IN THE HYDROGEN ABUNDANCE.
      DT2 = 0.5D0*DT*C4PI
C CENTRAL BOUNDARY CONDITION
      EMASS=EM(2)
      DEX_H = DT2*ECOD1(2)/EMASS
      EX_H(1) = DEX_H
C GENERAL CASE
      DO 10 I = 2,NPT-2
         EMASS=EM(I+1)-EM(I)
         DEX_H = DT2*(ECOD1(I+1)-ECOD1(I))/EMASS
         EX_H(I) = DEX_H
   10 CONTINUE
C SURFACE BOUNDARY CONDITION.
      EMASS = STOT-EM(NPT-1)
      DEX_H = -DT2*ECOD1(NPT-1)/EMASS
      EX_H(NPT-1) = DEX_H
C METAL DIFFUSION
      IF(LDIFZ.AND..NOT.LDOLI)THEN
C CENTRAL BOUNDARY CONDITION
         EMASS=EM(2)
         DEZ_H = DT2*ECOD1Z(2)/EMASS
         EZ_H(1) = DEZ_H
C GENERAL CASE
         DO I = 2,NPT-2
            EMASS=EM(I+1)-EM(I)
            DEZ_H = DT2*(ECOD1Z(I+1)-ECOD1Z(I))/EMASS
            EZ_H(I) = DEZ_H
         END DO
C SURFACE BOUNDARY CONDITION.
         EMASS = STOT-EM(NPT-1)
         DEZ_H = -DT2*ECOD1Z(NPT-1)/EMASS
         EZ_H(NPT-1) = DEZ_H
      ENDIF
      RETURN
      END
