C $$$$$$
      SUBROUTINE LAX_WENDROF2(DT,ECOD1_H,EM_H,EX,NPT,STOT,LDOLI)
      PARAMETER (JSON=5000)
      IMPLICIT REAL*8(A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
      COMMON/CONST1/ CLN,CLNI,C4PI,C4PIL,C4PI3L,CC13,CC23,CPI
C MHP 3/94 ADDED METAL DIFFUSION
      COMMON/GRAVS3/FGRY,FGRZ,LTHOUL,LDIFZ
      COMMON/GRAVEZ/ECOD1Z(JSON),ECOD1Z_H(JSON),ECOD2Z_H(JSON),
     *              EQCOD1Z_H(JSON),EQCOD2Z_H(JSON),EZ(JSON),
     *              EZ_H(JSON)
      DIMENSION ECOD1_H(JSON),EM_H(JSON),EX(JSON)
      SAVE

      DT2 = DT*C4PI
C CENTRAL BOUNDARY CONDITION
      EMASS=EM_H(1)
      DEX = DT2*ECOD1_H(1)/EMASS
      EX(1) = EX(1)+DEX
C    99 FORMAT(5X,1P2E15.7)
C GENERAL CASE
      DO 10 I = 2,NPT-1
         EMASS=EM_H(I)-EM_H(I-1)
         DEX = DT2*(ECOD1_H(I)-ECOD1_H(I-1))/EMASS
         EX(I) = EX(I)+DEX
   10 CONTINUE
C SURFACE BOUNDARY CONDITION.
      EMASS = STOT-EM_H(NPT-1)
      DEX = -DT2*ECOD1_H(NPT-1)/EMASS
      EX(NPT) = EX(NPT)+DEX
C MHP 3/94 ADDED METAL DIFFUSION.
      IF(LDIFZ.AND..NOT.LDOLI)THEN
         EMASS = EM_H(1)
         DEZ = DT2*ECOD1Z_H(1)/EMASS
         EZ(1) = EZ(1)+DEZ
C GENERAL CASE
         DO I = 2,NPT-1
            EMASS=EM_H(I)-EM_H(I-1)
            DEZ = DT2*(ECOD1Z_H(I)-ECOD1Z_H(I-1))/EMASS
            EZ(I) = EZ(I)+DEZ
         END DO
C SURFACE BOUNDARY CONDITION.
         EMASS = STOT-EM_H(NPT-1)
         DEZ = -DT2*ECOD1Z_H(NPT-1)/EMASS
         EZ(NPT) = EZ(NPT)+DEZ
      ENDIF
      RETURN
      END
