C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C LL4TH
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     THIS IS THE 4TH TABLE OF THE LAWRENCE LIVERMORE OPACITY TABLES.
C     IT CONTAINS THE OPACITIES FOR THE SURFACE ABUNDANCES OF X AND Z, AND
C     IS USED TO AVOID MANY INTERPOLATIONS TO THE SAME X.
      SUBROUTINE LL4TH(X)

      PARAMETER (NUMT=50)
      PARAMETER (NUMD=17)
      PARAMETER (NUMX=3)
      PARAMETER (NUMXT=NUMT*NUMX)
      PARAMETER (NUM4D=4*NUMD)
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT LOGICAL*4 (L)
C MHP 10/02 made array dimensions consistent
      PARAMETER (NP=100)
      DIMENSION C(4,NP)
C      DIMENSION C(4,NUMD)
C     OUTPUT OF LL4TH
      COMMON /LLOT4/XENV4,ZENV4,CFORD4(NUMT,NUM4D),KIPM1
      COMMON /LLOT42/XENV42,ZENV42,CFORD42(NUMT,NUM4D),KIPM12
C     GRIDS
      COMMON /GLLOT/GRIDT(NUMT),GRIDX(NUMX),GRHOT3(NUMD)
      COMMON /GLLOT2/GRIDT2(NUMT),GRIDX2(NUMX),GRHOT32(NUMD)
C     LL OPACITY TABLES
      COMMON /LLOT/OPACITY(NUMXT,NUMD),NUMXM,NUMTM
      COMMON /LLOT2/OPACITY2(NUMXT,NUMD),NUMXM2,NUMTM2
C     THE SPLINE COEFFICIENTS AND THE SHAPE OF THE LL TABLE.
      COMMON /LINTPL/ CFORD(NUMXT,NUM4D),NDS(NUMXT),NDD(NUMXT)
      COMMON /LINTPL2/ CFORD2(NUMXT,NUM4D),NDS2(NUMXT),NDD2(NUMXT)
C OPACITY COMMON BLOCKS - modified 3/09
      COMMON /NEWOPAC/ZLAOL1,ZLAOL2,ZOPAL1,ZOPAL2, ZOPAL951,
     +       ZALEX1, ZKUR1, ZKUR2,TMOLMIN,TMOLMAX,LALEX06,
     +       LLAOL89,LOPAL92,LOPAL95,LKUR90,LALEX95,L2Z
      SAVE

C     KEEP THE COMPOSITION OF THE 4TH TABLE.
      XENV4=X
      ZENV4=ZOPAL1
      CALL FINDEX(GRIDX,NUMX,X,M1)
      IF(M1.LT.0)M1=-M1
      IF(M1.GE.3)M1=2
      IF(M1.LE.0)STOP ' ERROR IN X GRID'
      KIPM1=M1
      DO IM2=1,NUMTM
         M1=KIPM1
         T6=GRIDT(IM2)
         M2=IM2
         INDEX1=IM2+(M1-1)*NUMTM
         NDSS=NDS(INDEX1)
         IF(NDSS.NE.1)STOP ' LL4TH NDSS '
         NDF=NDSS+NDD(INDEX1)-1
         DO IM3=NDSS,NDF
            RHOT3=GRHOT3(IM3)
            CALL YLLO2D(T6,RHOT3,M1,M2,M3,O0,OL0,QOD0,QOT0)
            CALL YLLO2D(T6,RHOT3,M1+1,M2,M3,O1,OL1,QOD1,QOT1)
            GRDNT=(X-GRIDX(M1))/(GRIDX(M1+1)-GRIDX(M1))
            OLF=(OL1-OL0)*GRDNT+OL0
            OF=10.0D0**OLF
C     CONVERSION FROM THE DERIVATIVE WITH CONSTANT RHOT3 TO CONSTANT RHO
            C(1,IM3)=OLF
         END DO
         CALL YSPLIN(GRHOT3,C,NDF)
         DO J=1,NDF
            DO I=1,4
               INDEX2=I+(J-1)*4
               CFORD4(IM2,INDEX2)=C(I,J)
            END DO
         END DO
      END DO



      IF (L2Z) THEN
         XENV42=X
         ZENV42=ZOPAL2
         CALL FINDEX(GRIDX2,NUMX,X,M1)
         IF(M1.LT.0)M1=-M1
         IF(M1.GE.3)M1=2
         IF(M1.LE.0)STOP ' ERROR IN X GRID'
         KIPM12=M1
         DO IM2=1,NUMTM2
            M1=KIPM12
            T6=GRIDT2(IM2)
            M2=IM2
            INDEX1=IM2+(M1-1)*NUMTM2
            NDSS=NDS2(INDEX1)
            IF(NDSS.NE.1)STOP ' LL4TH Z1 CHECK NDSS '
            NDF=NDSS+NDD2(INDEX1)-1
            DO IM3=NDSS,NDF
               RHOT3=GRHOT32(IM3)
               CALL YLLO2D2(T6,RHOT3,M1,M2,M3,O0,OL0,QOD0,QOT0)
               CALL YLLO2D2(T6,RHOT3,M1+1,M2,M3,O1,OL1,QOD1,QOT1)
               GRDNT=(X-GRIDX2(M1))/(GRIDX2(M1+1)-GRIDX2(M1))
               OLF=(OL1-OL0)*GRDNT+OL0
               OF=10.0D0**OLF
C CONVERSION FROM THE DERIVATIVE WITH CONSTANT RHOT3 TO CONSTANT RHO
               C(1,IM3)=OLF
            END DO
            CALL YSPLIN(GRHOT32,C,NDF)
            DO J=1,NDF
               DO I=1,4
                  INDEX2=I+(J-1)*4
                  CFORD42(IM2,INDEX2)=C(I,J)
               END DO
            END DO
         END DO
      END IF



      RETURN
      END
