C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     LOCATE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C GIVEN AN ARRAY XX OF LENGTH N, AND GIVEN A VALUE X, RETURNS
C A VALUE J SUCH THAT X IS BETWEEN XX(J) AND XX(J+1).  X=0 OR N
C THEN OUT OF RANGE.
C
      SUBROUTINE LOCATE(XX, N, X, J)
      IMPLICIT REAL*8 (A-H,O-Z)
      DIMENSION XX(N)
      SAVE
      JL = 0
      JU = N+1
 10   IF (JU-JL.GT.1) THEN
         JM = (JU+JL)/2
         IF((XX(N).GT.XX(1)).EQV.(X.GT.XX(JM))) THEN
            JL = JM
         ELSE
            JU = JM
         END IF
         GO TO 10
      END IF
      J = JL
      IF((J .EQ. 0) .AND. (X .GT. 0.99D0*XX(1)))THEN
         J = 1
      END IF
      IF((J .EQ. N) .AND. (X .LT. 1.01D0*XX(N)))THEN
         J = N-1
      END IF
      RETURN
      END
