C MHP 10/01
C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
C MASS LOSS DRIVER ROUTINE
C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

C This is experimental code and valid for Allard atmospheres only.
C   llp  06/15/2009

      SUBROUTINE MASSLOSS(BL,DAGE,DELTS,HCOMP,HD,HJM,HP,HR,HS,
     *                    HS1,HS2,HSTOT,HT,JENV,LNEW,M,OMEGA,SMASS,
     *                    TEFFL,SENVOLD,LNEWFIT)
      PARAMETER (JSON=5000)
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
      DIMENSION HCOMP(15,JSON),HD(JSON),HP(JSON),HS(JSON),
     *          HS1(JSON),HS2(JSON),HT(JSON),HJM(JSON),
     *          OMEGA(JSON),HR(JSON),FXION(3)
      COMMON/ATMPRT/TAU,AP,AT,AD,AO,AFXION(3)
      COMMON/CONST/CLSUN,CLSUNL,CLNSUN,CMSUN,CMSUNL,CRSUN,CRSUNL,CMBOL
      COMMON/CONST1/ CLN,CLNI,C4PI,C4PIL,C4PI3L,CC13,CC23,CPI
      COMMON/CONST2/CGAS,CA3,CA3L,CSIG,CSIGL,CGL,CMKH,CMKHN
      COMMON/CONST3/CDELRL,CMIXL,CMIXL2,CMIXL3,CLNDP,CSECYR
      COMMON/MASSCHG/DMDT0,FCZDMDT,FTOTDMDT,COMPACC(15),CREIM,
     *               LREIMER,LMDOT
      COMMON/MASSCHG2/SACC,SCEN,SMASS0,DLOGT,DLOGP
      COMMON/DEUTER/DRATE(JSON),DRATE0(JSON),FMASSACC,JCZ
      COMMON/SCRTCH/SESUM(JSON),SEG(7,JSON),SBETA(JSON),SETA(JSON),
     *LOCONS(JSON),SO(JSON),SDEL(3,JSON),SFXION(3,JSON),SVEL(JSON),SCP(JSON)
C G Somers 3/17, ADDING NEW TAUCZ COMMON BLOCK
      COMMON/OVRTRN/LNEWTCZ,LCALCENV,TAUCZ,TAUCZ0,PPHOT,PPHOT0,FRACSTEP
C MHP 5/02 EFFICIENCY FACTOR FOR THE THERMAL ENERGY CONTENT
C OF ACCRETED MATTER.
      DATA FACC/1.0D0/
      SAVE
C INITIALIZE MASS LOSS AT DEFAULT RATE
      DMDT = DMDT0
      IF(LMDOT)THEN
         LDOMDOT = .TRUE.
      ELSE
         LDOMDOT = .FALSE.
         LNEWFIT = .FALSE.
         GOTO 9999
      ENDIF
C      IF(.NOT.LDOMDOT)RETURN
C TEFFL IS THE BASE 10 LOG OF THE EFFECTIVE TEMPERATURE
C COMPUTE GLOBAL QUANTITIES (RADIUS,MASS,AGE) IN CGS UNITS.
C RADIUS
      RL = 0.5d0*(BL + CLSUNL - C4PIL - CSIGL - 4.0D0*TEFFL)
      RTOT = 10.0D0**RL
C MASS
      STOT = SMASS*CMSUN
C AGE
      AGETOT = DAGE*1.0D9*CSECYR
C USE A REIMERS FORMULA TO COMPUTE MDOT IF DESIRED; OVERWRITES
C CONSTANT MDOT.  IN THIS EXPRESSION MDOT=K*L/G/R.
      IF(LDOMDOT .AND.LREIMER)THEN
         GSURF = 10.0D0**(CGL)*STOT/RTOT**2
         DMDT = CREIM*10.0D0**(BL + CLSUNL)/GSURF/RTOT
      ENDIF
C 02/12 MHP TAUCZ NOW COMPUTED PRIOR TO CALL IN MIXCZ
C CONVECTIVE OVERTURN TIMESCALE
      IF(JENV.LT.M)THEN
C         TAUCZ = 0.0D0
C         DO I = JENV+1,M
C            V = 0.5D0*(SVEL(I-1)+SVEL(I))
C            DR = 10.0D0**(HR(I))-10.0D0**(HR(I-1))
C            IF(V.GT.0.0D0)THEN
C               TAUCZ = TAUCZ + DR/V
C            ENDIF
C         END DO
         WRITE(*,*)TAUCZ/CSECYR,RTOT/CRSUN
         JCZ = JENV
      ELSE
         TAUCZ = 0.0D0
         JCZ = M
      ENDIF
C MHP 8/10
C THE RUNNING TOTAL OF THE MASS OF THE
C CONVECTIVE ENVELOPE, NEEDED ELSEWHERE AS WELL
      SUMDM = 0.0D0
      DO J = JENV, M
         SUMDM = SUMDM + HS2(J)
      END DO
C COMPUTE THE MEAN MOLECULAR WEIGHT FOR THE CZ
      IF(DMDT.GT.0.0D0)THEN
         LNEWFIT = .TRUE.
         T = 10.0D0**HT(JENV)
         P = 10.0D0**HP(JENV)
         D = 10.0D0**HD(JENV)
         BETA = 1.0D0- (CA3*T**4/P)
         RMU = P*BETA/(D*T)
C FROM THE VIRIAL THEOREM, A MAXIMUM OF
C 1/2 OF THE GRAVITATIONAL POTENTIAL ENERGY OF
C ACCRETED MATTER WILL BE CONVERTED INTO KINETIC
C ENERGY.  THE PARAMETER FACC IS USED TO INFER
C THE KINETIC ENERGY PER GRAM WHICH IS COMPARED
C WITH THE MEAN THERMAL ENERGY CONTENT OF THE
C CONVECTION ZONE.
         EACC = FACC*STOT*(10.0D0**CGL)/RTOT
         EACC0 = EACC
C DETERMINE THE MASS-WEIGHTED THERMAL ENERGY (PER GM)
C IN EACH SHELL OF THE CONVECTIVE ENV.
         SUMETH = 0.0D0
C         SUMDM = 0.0D0
         ETHACCBAR = 0.0D0
         SCEN = 0.0D0
         DO J = JENV, M
            T = 10.0D0**HT(J)
            P = 10.0D0**HP(J)
            D = 10.0D0**HD(J)
            R = 10.0D0**HR(J)
            DELACC = 0.5D0*EACC*(RTOT/R - 1.0D0)
            ETHACC = EACC + DELACC
            ETHACCBAR = ETHACCBAR+HS2(J)*ETHACC
            BETA = 1.0D0- (CA3*T**4/P)
            RMU = P*BETA/(D*T)
            SLOCAL = RMU*(1.5D0*LOG(T)-LOG(D))
            SCEN = SCEN+SLOCAL*HS2(J)
C THE THERMAL ENERGY PER GM IN THE JTH SHELL IS
            ETH = P*BETA/D
C THE RUNNING TOTAL OF THERMAL ENERGY THROUGHOUT THE
C CONVECTIVE ENVELOPE IS
            SUMETH = SUMETH + ETH*HS2(J)
C THE RUNNING TOTAL OF THE MASS OF THE
C CONVECTIVE ENVELOPE IS
C            SUMDM = SUMDM + HS2(J)
         END DO
C THE AVERAGE THERMAL ENERGY OF THE UNPERTURBED CE (W/O ACCN) IS
         ETHAV = SUMETH/SUMDM
         EACC = ETHACCBAR/SUMDM
         SCEN = SCEN/SUMDM
         LPRT = .FALSE.
         GL = CGL + HSTOT - 2.0D0*RL
C This is experimental code and valid for Allard atmospheres only.
C   llp  06/15/2009
         CALL ALSURFP(TEFFL,GL,LPRT,LAlFail)
         T = 10.0D0**AT
         P = 10.0D0**AP
         TL = AT
         PL = AP
         X = HCOMP(1,M)
         Z = HCOMP(3,M)
         LDERIV = .FALSE.
         KSAHA = 1
         LATMO = .TRUE.
         CALL EQSTAT(TL,T,PL,P,DL,D,X,Z,BETA,BETAI,BETA14,FXION,RMU,
     *        AMU,EMU,ETA,QDT,QDP,QCP,DELA,QDTT,QDTP,QAT,QAP,QCPT,
     *        QCPP,LDERIV,LATMO,KSAHA)
         BETA = 1.0D0- (CA3*T**4/P)
         RMU = P*BETA/(D*T)
         SACC = RMU*(1.5D0*LOG(T)-LOG(D))
C         WRITE(*,911)TL,PL,SACC,SCEN
C  911     FORMAT(' TSUR,PSUR ',2F8.5,' SACC ',1PE12.3,' SCORE ',E12.3)
C ALTERNATE EXPRESSION FOR SURFACE PRESSURE AND LUMINOSITY, FROM STAHLER 1988
         IF(FACC.GT.0.0D0)THEN
            DMDT2 = DMDT*CMSUN/CSECYR
            P = DMDT2/C4PI*SQRT(2.0D0*FACC*10.0D0**GL/RTOT**3)
            T = (DMDT2*EACC0*0.75D0/C4PI/RTOT**2/CSIG)**0.25D0
            PL = LOG10(P)
            TL = LOG10(T)
            CALL EQSTAT(TL,T,PL,P,DL,D,X,Z,BETA,BETAI,BETA14,FXION,RMU,
     *        AMU,EMU,ETA,QDT,QDP,QCP,DELA,QDTT,QDTP,QAT,QAP,QCPT,
     *        QCPP,LDERIV,LATMO,KSAHA)
            BETA = 1.0D0- (CA3*T**4/P)
            RMU = P*BETA/(D*T)
            SACC2 = RMU*(1.5D0*LOG(T)-LOG(D))
C            WRITE(*,911)TL,PL,SACC2,SCEN
C            SACC = MAX(SACC,SACC2)
            SCEN = 0.0D0
C            SCEN = SACC2 - SACC
         ELSE
            SCEN = 0.0D0
         ENDIF
      ENDIF
C CALL MASS LOSS OR ACCRETION ROUTINE
      IF(LDOMDOT)CALL MDOT(DELTS,HCOMP,HD,HJM,HP,HR,HS,HS1,HS2,
     *          HSTOT,HT,JENV,LNEW,M,OMEGA,RMU,RTOT,SMASS,DMDT,
     *          EACC,ETHAV,SUMDM,SENVOLD)
 9999 CONTINUE
      RETURN
      END
