C$$$$$$
      SUBROUTINE MCOWIND(BL,DT,HICZ,IT,OMEGAS,SMASS,
     *                  TEFFL,WOLD,WIND1,WIND2)

      PARAMETER (JSON=5000)
      IMPLICIT REAL*8(A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
      COMMON/CONST/CLSUN,CLSUNL,CLNSUN,CMSUN,CMSUNL,CRSUN,CRSUNL,CMBOL
      COMMON/CONST1/ CLN,CLNI,C4PI,C4PIL,C4PI3L,CC13,CC23,CPI
      COMMON/CONST2/CGAS,CA3,CA3L,CSIG,CSIGL,CGL,CMKH,CMKHN
C MHP 8/17 ADDED EXCEN, C_2 TO COMMON BLOCK FOR MATT ET AL. 2012 CENT. TERM
      COMMON/CWIND/WMAX,EXMD,EXW,EXTAU,EXR,EXM,EXL,EXPR,CONSTFACTOR,
     *             STRUCTFACTOR,EXCEN,C_2,LJDOT0
C      COMMON/CWIND/WMAX,EXMD,EXW,EXTAU,EXR,EXM,CONSTFACTOR,STRUCTFACTOR,LJDOT0
C MHP 3/09 ADDED OPTION TO SCALE THE SATURATION RATE BY THE OVERTURN TIMESCALE
      COMMON/DEUTER/DRATE(JSON),DRATE0(JSON),FMASSACC,JCZ
C G Somers 3/17, ADDING NEW TAUCZ COMMON BLOCK
      COMMON/OVRTRN/LNEWTCZ,LCALCENV,TAUCZ,TAUCZ0,PPHOT,PPHOT0,FRACSTEP
      CHARACTER*3 AWIND
C KC 2025-05-30 reordered common block elements
C       COMMON/PMMWIND/AWIND,LMWIND,LROSSBY,LBSCALE,PMMA,PMMB,PMMC,PMMD,PMMM,
C      *         PMMJD,PMMMD,PMMSOLP,PMMSOLW,PMMSOLTAU
      COMMON/PMMWIND/PMMA,PMMB,PMMC,PMMD,PMMM,PMMJD,PMMMD,PMMSOLP,PMMSOLW,PMMSOLTAU,
     *         LMWIND,LROSSBY,LBSCALE,AWIND
      SAVE
C  COWIND RETURNS THE CHANGE IN THE ANGULAR VELOCITY OF THE SURFACE
C  CONVECTION ZONE OF A STAR WHICH IS EXPERIENCING ANGULAR MOMENTUM LOSS.
C
C  INPUT VARIABLES:
C
C       DECLARED
C  BL : TOTAL LUMINOSITY
C  DT : DIFFUSION TIMESTEP.
C  HICZ : TOTAL MOMENT OF INERTIA OF THE SURFACE C.Z.
C  IT : ITERATION NUMBER (IN THE DIFFUSION ROUTINES).
C  OMEGAS : SURFACE ANGULAR VELOCITY AT THE END OF THE PREVIOUS ITERATION.
C  SMASS : STELLAR MASS (SOLAR UNITS)
C  TEFFL : STELLAR EFFECTIVE TEMPERATURE.
C  WOLD : SURFACE ANGULAR VELOCITY AT THE BEGINNING OF THE TIMESTEP.
C       IN COMMON BLOCKS
C
C  EXMD,EXW,EXTAU,EXR,EXM,FACTOR : USER PARAMETERS WHICH VARY THE STRENGTH
C  OF ANGULAR MOMENTUM LOSS AND ITS DEPENDENCE ON SURFACE ROTATION RATE
C  AND OTHER STELLAR PARAMETERS.
C
C  OUTPUT VARIABLES
C
C  WIND1,WIND2:CHANGE IN ANGULAR VELOCITY OF THE SURFACE C.Z. FOR THE TIMESTEP
C  BASED ON THE ANGULAR VELOCITY AT THE BEGINNING AND END OF THE TIMESTEP
C  RESPECTIVELY.
C
C  WIND1 AND WIND2 ARE INCORPORATED INTO THE DIFFUSION EQUATIONS;
C  THEY ARE AVERAGED TO FIND THE TOTAL ANGULAR MOMENTUM LOSS FOR THE
C  TIMESTEP.
C
C RUN OLD WINDLAW IF LMWIND = FALSE
      IF(.NOT.LMWIND)THEN
         CALL COWIND(BL,DT,HICZ,IT,OMEGAS,SMASS,
     *                  TEFFL,WOLD,WIND1,WIND2)
         GOTO 9999
      ENDIF
C
C G Somers 8/17 CREATE ROTATION DUMMY VARIABLES.
      WFIRST = WOLD
      WNOW = OMEGAS
C
C ADD ROSSBY SCALING TO WMAX = CRITICAL W FOR THE SUN.
      IF(LROSSBY)THEN
C MHP 8/17 CORRECTED TAUCZ CALCULATION TO INTERPOLATE PROPERLY IN TIMESTEP
         TCZ = TAUCZ0+FRACSTEP*(TAUCZ-TAUCZ0)
         WSAT = WMAX*PMMSOLTAU/TCZ
C G Somers 08/17 IF ADDING ADDITIONAL B SCALING, ADD ADDITIONAL TAUCZ TERM.
         IF(LBSCALE)THEN
            WFIRST = WFIRST*TCZ/PMMSOLTAU
            WNOW = WNOW*TCZ/PMMSOLTAU
            WSAT = WSAT*TCZ/PMMSOLTAU
         ENDIF
      ELSE
         WSAT = WMAX
      ENDIF
C
C G Somers 3/17, COMMENTING OUT OLD WIND LAW COEFFICIENT
C CALCULATION. ADDING NEW PMM-STYLE VERSION
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C      RL=0.5D0*(BL+CLSUNL-C4PIL-CSIGL-4.D0*TEFFL)
C      RTOT = EXP(CLN*RL)
C DMDOT IS THE MASS LOSS RATE IN SOLAR MASSES PER YEAR.
C      DMDOT = 2.0D-14
C DJ/DT = DT*FACTOR*(DMDOT/1.0D-14)**EXMD*OMEGA**EXW*(M/MSUN)**EXM
C         *(R/RSUN)**EXR
C  THE CONSTANT AND EXPONENTS ARE SET IN PARMIN BASED ON THE INPUT
C  INDEX ALFA;SEE PARMIN FOR DETAILS ON THE DEPENDENCE OF EACH ON ALFA.
C      C = DT/HICZ*FACTOR*(DMDOT/1.0D-14)**EXMD
C     *    *(RTOT/CRSUN)**EXR*SMASS**EXM
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C NEW CALCULATION. CALL AMCALC TO SET "STRUCTFACTOR"
C
      CALL AMCALC(SMASS,BL,TEFFL)
C
C CALCULATE THE NEW WIND COEFFICIENT.
C
      C = (DT/HICZ)*CONSTFACTOR*STRUCTFACTOR
C MHP 8/17 ADDED CENTRIFUGAL REDUCTION TERM FROM MATT+2012 ApJ 754, L26
C NOTE THAT THIS IS IMPLEMENTED HERE RELATIVE TO THE SUN
C      C_2 = 0.0506
      FSUN = 0.5*PMMSOLW**2*CRSUN**3/EXP(CLN*GL)/CMSUN
C     RADIUS
      RL = 0.5D0*(BL+CLSUNL-C4PIL-CSIGL-4.D0*TEFFL)
      FCORR1 = 0.5*WOLD**2*EXP(CLN*(3.0*RL-CGL))/SMASS/CMSUN
      FCORR2 = 0.5*OMEGAS**2*EXP(CLN*(3.0*RL-CGL))/SMASS/CMSUN
      FCEN1 = ((C_2**2+FSUN)/(C_2**2+FCORR1))**EXCEN
      FCEN2 = ((C_2**2+FSUN)/(C_2**2+FCORR2))**EXCEN
C
C G Somers, END
      WP = MIN(WFIRST,WSAT)
      WN = MIN(WNOW,WSAT)
      WIND1 = C*WP**(EXW-1.0D0)*WOLD*FCEN1
      TEMP = C*WN**(EXW-1.0D0)*OMEGAS*FCEN2
C      WIND1 = C*WP**(EXW-1.0D0)*WOLD
C      TEMP = C*WN**(EXW-1.0D0)*OMEGAS
      IF(IT.EQ.1) THEN
         WIND2 = TEMP
      ELSE
         WIND2 = 0.5D0*(WIND2+TEMP)
      ENDIF
 9999 CONTINUE
      RETURN
      END
