C
C
C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
C MHDTBL
C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
      SUBROUTINE MHDTBL(FMHD1,FMHD2,FMHD3,FMHD4,FMHD5,FMHD6,FMHD7,FMHD8)
      IMPLICIT REAL*8(A-H,O-Z)
      IMPLICIT LOGICAL*4(L)

C     FOR SET TABLES
C MHP 8/25 Removed un-used file names and file names from common blocks
      CHARACTER*256 FMHD1, FMHD2, FMHD3, FMHD4, FMHD5, FMHD6, FMHD7, FMHD8
C      COMMON/LUFNM/ FLAST, FFIRST, FRUN, FSTAND, FFERMI,
C     1    FDEBUG, FTRACK, FSHORT, FMILNE, FMODPT,
C     2    FSTOR, FPMOD, FPENV, FPATM, FDYN,
C     3    FLLDAT, FSNU, FSCOMP, FKUR,
C     4    FMHD1, FMHD2, FMHD3, FMHD4, FMHD5, FMHD6, FMHD7, FMHD8
      COMMON/MHD/LMHD,IOMHD1,IOMHD2,IOMHD3,IOMHD4,IOMHD5,IOMHD6,
     1           IOMHD7, IOMHD8
      COMMON/CCOUT2/LDEBUG,LCORR,LMILNE,LTRACK,LSTPCH
C       DATA UMOD /2.302585092994046 D0/
      SAVE

C     SET MHD EQUATION OF STATE
C     USES 3 ZAMS-TYPE TABLES AND OPTIONALLY 5 CENTER-TYPE TABLES.
C
      OPEN(UNIT=IOMHD1, FILE=FMHD1, STATUS='OLD',
     1    FORM='UNFORMATTED')
      OPEN(UNIT=IOMHD2, FILE=FMHD2, STATUS='OLD',
     1    FORM='UNFORMATTED')
      OPEN(UNIT=IOMHD3, FILE=FMHD3, STATUS='OLD',
     1    FORM='UNFORMATTED')
      OPEN(UNIT=IOMHD4, FILE=FMHD4, STATUS='OLD',
     1    FORM='UNFORMATTED')
      OPEN(UNIT=IOMHD5, FILE=FMHD5, STATUS='OLD',
     1    FORM='UNFORMATTED')
      OPEN(UNIT=IOMHD6, FILE=FMHD6, STATUS='OLD',
     1    FORM='UNFORMATTED')
      OPEN(UNIT=IOMHD7, FILE=FMHD7, STATUS='OLD',
     1    FORM='UNFORMATTED')
      OPEN(UNIT=IOMHD8, FILE=FMHD8, STATUS='OLD',
     1    FORM='UNFORMATTED')

      CALL MHDST(IOMHD1, IOMHD2, IOMHD3, IOMHD4, IOMHD5, IOMHD6,
     1           IOMHD7, IOMHD8)
C     END MHD TABLE SETTING
      CLOSE(IOMHD1)
      CLOSE(IOMHD2)
      CLOSE(IOMHD3)
      CLOSE(IOMHD4)
      CLOSE(IOMHD5)
      CLOSE(IOMHD6)
      CLOSE(IOMHD7)
      CLOSE(IOMHD8)
      RETURN
      END
