C $$$$$$
C       SUBROUTINE MOMI(ETA2,HD,HR,HS,HS2,JSTART,JEND,OMEGA,R0,HI,QIW,M)  ! KC 2025-05-31
      SUBROUTINE MOMI(ETA2,HR,HS,HS2,JSTART,JEND,OMEGA,R0,HI,QIW)

      PARAMETER (JSON=5000)
      IMPLICIT REAL*8(A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
      COMMON/CCOUT/LSTORE,LSTATM,LSTENV,LSTMOD,LSTPHYS,LSTROT,LSCRIB,LSTCH,LPHHD
      COMMON/CONST1/ CLN,CLNI,C4PI,C4PIL,C4PI3L,CC13,CC23,CPI
      COMMON/CONST2/CGAS,CA3,CA3L,CSIG,CSIGL,CGL,CMKH,CMKHN
      COMMON/LUOUT/ILAST,IDEBUG,ITRACK,ISHORT,IMILNE,IMODPT,ISTOR,IOWR
      COMMON/ROT/WNEW,WALPCZ,ACFPFT,ITFP1,ITFP2,LROT,LINSTB,LWNEW
C       DIMENSION HD(JSON),HR(JSON),HS2(JSON),R0(JSON),ETA2(JSON),HI(JSON)  ! KC 2025-05-31
      DIMENSION HR(JSON),HS2(JSON),R0(JSON),ETA2(JSON),HI(JSON)
      DIMENSION OMEGA(JSON),HS(JSON),QIW(JSON)
      SAVE

C  FIND THE MOMENT OF INERTIA (HI) AND DI/D(OMEGA) (QIW).
C  MOMI ASSUMES THAT SHAPE HAS ALREADY BEEN CALLED.
C  MOMENT OF INERTIA IS CALCULATED BY THE METHOD USED IN WAI-YUEN LAW'S
C  THESIS(YALE,1980) P.61.
      IF(JSTART.EQ.1) THEN
         R0P = 0.0D0
         RPHIP = 0.0D0
      ELSE
         R0P = DLOG(R0(JSTART - 1))
         RPHIP = CLN*HR(JSTART - 1)
      ENDIF
      CON = CC13*5.0D0/DEXP(CLN*CGL)
      IF(WALPCZ.NE.0.0D0)THEN
         DO I = JSTART,JEND
            HI(I) = CC23*HS2(I)*EXP(CLN*2.0D0*HR(I))
            QIW(I) = 0.0D0
         END DO
         IF(JSTART.EQ.1)THEN
             RAD = 0.5D0*(HR(1)+HR(2))
             HI(1) = 0.4D0*HS2(1)*EXP(CLN*2.0D0*RAD)
         ENDIF
         RETURN
      ENDIF
      DO 20 I = JSTART,JEND
C  QR0R = D LN R0/ D LN R
C
         QR0R = 1.0D0
         H0 = CC23*HS2(I)*DEXP(CLN*2.0D0*HR(I))
         R03 = R0(I)**3
         RPHI3 = DEXP(CLN*3.0D0*HR(I))
         R0R = (R03/RPHI3)*R0(I)**2
         A = CON*OMEGA(I)**2*R03/(DEXP(CLN*HS(I))*(2.0D0+ETA2(I)))
         ETA2X = ETA2(I)
C  EVALUATE INTEGRAL AT THE ZONE CENTER
         CALL INTMOM(A,ETA2X,QR0R,R0R,HIM,QIWM)
         HI(I) = HIM*HS2(I)
         QIW(I) = QIWM*HS2(I)
         R0P = DLOG(R0(I))
         RPHIP = CLN*HR(I)
   20 CONTINUE

      RETURN
      END
