C
C     OPAL EQUATION OF STATE
C
C     IMPLIMENTED BY YC    (FEB. 21, 1995)
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C INDEX TO THIS FILE:
C     SUBROUTINE OEQOS
C     SUBROUTINE MU
C     SUBROUTINE ESAC
C     SUBROUTINE T6RINTERP
C     SUBROUTINE READCO
C     FUNCTION QUAD
C     FUNCTION GMASS
C     SUBROUTINE RADSUB
C     FUNCTION RHOOFP
C
C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
C MEQOS
C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
      SUBROUTINE OEQOS(T10,T,P10,P,D10,D,XC,Z,BETA,BETAI,
     1 BETA14,RMU,AMU,EMU,QDT,QDP,QCP,DELA,*)

      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
C       DIMENSION ATOMWT(4)
      COMMON/COMP/XENV,ZENV,ZENVM,AMUENV,FXENV(12),XNEW,ZNEW,STOTAL,
     *     SENV
      COMMON/CTLIM/ATIME(14),TCUT(5),TSCUT,TENV0,TENV1,TENV,TGCUT
      COMMON/CONST1/ CLN,CLNI,C4PI,C4PIL,C4PI3L,CC13,CC23,CPI
      COMMON/CONST2/CGAS,CA3,CA3L,CSIG,CSIGL,CGL,CMKH,CMKHN
      COMMON/CCOUT2/LDEBUG,LCORR,LMILNE,LTRACK,LSTPCH
      COMMON/LUOUT/ILAST,IDEBUG,ITRACK,ISHORT,IMILNE,IMODPT,ISTOR,IOWR

      PARAMETER ( IVARX = 25 )
      PARAMETER (CNVS = 0.434294481D0 )
      PARAMETER (ZERO = 0.0D0)

      COMMON/E/ ESACT,EOS(10)

C       DATA NZP1/12/
C       DATA ATOMWT/0.9921D0,0.24975D0,0.08322D0,0.4995D0/
      SAVE
C
C      CA3=2.5214D-15
C
      T=10.0D0**T10
      P=10.0D0**P10
      T6=T/1.0D6
      P12=P/1.0D12
      IF(T6.LT.0.0050D0.OR.T6.GT.100.0D0)RETURN 1
      X=XC
      ZTAB=Z

      IRAD=1
      IORDER=10

C       R=RHOOFP(X,ZTAB,T6,P12,IRAD)  ! KC 2025-05-31
      R=RHOOFP(X,T6,P12,IRAD)
      IF(R.LE.-998.0D0)THEN
         RETURN 1
      ENDIF
      D=R
      D10=DLOG10(D)

C       CALL ESAC(X,ZTAB,T6,R,IORDER,IRAD,*999)  ! KC 2025-05-31
      CALL ESAC(X,T6,R,IORDER,IRAD,*999)

      IF(ABS((P12-EOS(1))/P12).GT.0.5D-6)THEN
         WRITE(ISHORT,*)P12,EOS(1)
         STOP ' ERROR IN OEQOS PTOT'
      ENDIF
      QDP=1.0D0/EOS(6)
      QDT= -EOS(7)/ EOS(6)

      QCP=1.0D6*EOS(5)*EOS(8)/EOS(6)
      DELA=1.0D0/EOS(9)

      BETA14=(2.521971383D-3*T6*T6)*(T6*T6/P12)
      BETA=1.0D0-BETA14
      BETAI=1.0D0/BETA
      RMU=P*BETA/(D*T)
      CALL MU(T,P,D,XC,Z,RMU2,AMU,EMU,BETA)
      IF(EMU.LE.0.0D0)THEN
      EMU=0.0D0
      AMU=RMU/CGAS-EMU
      ENDIF

      RETURN
  999 WRITE(ISHORT, *)'WARNNING... OPAL TBL FAIL'

      RETURN 1
      END
