C ACM ALGORITHM 574
C
C SHAPE-PRESERVING OSCULATORY QUADRATIC SPLINES
C
C BY D.F. MCALLISTER AND J.A. ROULIER
C
C ACM TRANSACTIONS ON MATHEMATICAL SOFTWARE, SEPTEMBER, 1981.
C
C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
C OSPLIN
C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
      SUBROUTINE OSPLIN(XVAL,YVAL,XTAB,YTAB,N,K)
      PARAMETER (JSON=5000)
      REAL*8 XVAL(JSON),YVAL(JSON),XTAB(JSON),YTAB(JSON),
     *       M(JSON),EPS
      INTEGER N,K,ERR
C
C   X CONTAINS THE ABSCISSAS OF THE POINTS OF INTERPOLAION.
C
C   Y CONTAINS THE ORDINATES OF THE POINTS OF INTERPOLATION.
C
C   N IS THE NUMBER OF DATA POINTS.
C
C   K IS THE NUMBER OF POINTS AT WHICH THE SPLINE IS TO BE EVALUATED.
C
C
C UPON EXIT FROM SUBROUTINE 'SLOPES'--
C
C   M CONTAINS THE COMPUTED FIRST DERIVATIVES AT EACH DATA POINT.
C
C----------------------------------------------------------------------
C
      save

C CALCULATE THE SLOPES AT EACH DATA POINT.
      CALL SLOPES(XTAB,YTAB,M,N)
C
C SET THE ERROR TOLERANCE EPS, WHICH IS USED IN SUBROUTINE 'CHOOSE'.
      EPS=1.D-04
C CALL MEVAL TO EVALUATE THE SPLINE AT THE RUN OF POINTS XVAL.
      CALL MEVAL(XVAL,YVAL,XTAB,YTAB,M,N,K,EPS,ERR)

      RETURN
      END
