C $$$$$$
      SUBROUTINE OVROT(HCOMP,HD,HP,HR,HS,HT,LC,M,LCZ,MRZONE,MXZONE,
     *                 NRZONE,NZONE)

      PARAMETER (JSON=5000)
      IMPLICIT REAL*8(A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
      DIMENSION HCOMP(15,JSON),HD(JSON),HP(JSON),HR(JSON),HS(JSON),
     *  HT(JSON),LC(JSON),LCZ(JSON),MRZONE(13,2),MXZONE(12,2),
     *  MXZON0(12,2)
      save

C ISOLATE CONVECTIVE REGIONS INCLUDING OVERSHOOT.
      CALL CONVEC(HCOMP,HD,HP,HR,HS,HT,LC,M,MRZONE,MXZONE,MXZON0,
     *             JCORE,JENV,NRZONE,NZONE,NZONE0)
      DO 10 J = 1,NRZONE
         DO 5 I = MRZONE(J,1),MRZONE(J,2)
C KC 2025-05-30 ADDED IF CHECK TO AVOID RUNTIME ERROR.
            IF (I .GT. 0) LCZ(I) = .FALSE.
    5    CONTINUE
   10 CONTINUE
      DO 20 J = 1,NZONE
         DO 15 I = MXZONE(J,1),MXZONE(J,2)
            LCZ(I) = .TRUE.
   15    CONTINUE
   20 CONTINUE

      RETURN
      END
