C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     READ PURE Z LAOL89
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE RDZLAOL(FPUREZ)
C MHP 10/02 vector v not used
C      SUBROUTINE RDZLAOL(V)

      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
      REAL*8 OLAOL(12,104,52),OXA(12),OT(52),ORHO(104),TOLLAOL
      REAL*8 DUMMY(104)
      REAL*8 ZLAOL1,ZLAOL2,ZOPAL1,ZOPAL2, ZOPAL951,
     *    ZALEX1, ZKUR1, ZKUR2  ! ZOPAL952, ZALEX2
      CHARACTER*256 FPUREZ

C MHP 8/25 Removed character file names from common block
      COMMON/NWLAOL/OLAOL, OXA, OT, ORHO, TOLLAOL,
     *  IOLAOL, NUMOFXYZ, NUMRHO, NUMT, LLAOL, LPUREZ, IOPUREZ
C DBG 12/95 ARRAYS FOR PURE Z TABLE
      COMMON/ZLAOL/ZOLAOL(104,52), ZOT(52), ZORHO(104),
     *  NUMRHOZ, NUMTZ
      COMMON/LUOUT/ILAST,IDEBUG,ITRACK,ISHORT,IMILNE,IMODPT,ISTOR,IOWR
C OPACITY COMMON BLOCKS - modified 3/09
      COMMON /NEWOPAC/ZLAOL1,ZLAOL2,ZOPAL1,ZOPAL2, ZOPAL951,
     +       ZALEX1, ZKUR1, ZKUR2,TMOLMIN,TMOLMAX,LALEX06,
     +       LLAOL89,LOPAL92,LOPAL95,LKUR90,LALEX95,L2Z
C      DIMENSION V(12)
      SAVE

      OPEN(UNIT=IOPUREZ, FILE=FPUREZ,FORM='FORMATTED',
     *        STATUS='OLD')
C     READ IN ARRAY SIZES
      READ(IOPUREZ,100)N,NUMRHOZ,NUMTZ
  100 FORMAT(/,18X,I2,9X,I3,14X,I3)
      IF(N.NE.1.OR.NUMRHOZ.GT.104.OR.NUMTZ.GT.52) THEN
         WRITE(ISHORT,*)' Z OPACITY INPUT ERROR.'
         STOP
      END IF
      READ(IOPUREZ,120)(DUMMY(I),I=1,11)
  120 FORMAT(47X,F8.5,//,1P6E12.5,/,1P4E12.5)
      READ(IOPUREZ,131)DUMMY(1)
  131 FORMAT(54X,F8.5,///////)
C     READ IN H MASS FRACTIONS OF TABLE
      READ(IOPUREZ,140)DUMMY(1)
  140 FORMAT(/,(1P6E12.5))
C     READ IN DENSITY GRID OF TABLE
      READ(IOPUREZ,150)(ZORHO(II),II=1,NUMRHOZ)
  150 FORMAT(/,(1P6E12.5))
C     READ IN TEMPERATURE GRID OF TABLE
      READ(IOPUREZ,160)(ZOT(II),II=1,NUMTZ)
  160 FORMAT(/,(1P6E12.5))
C     READ IN PURE Z OPACITIES
      READ(IOPUREZ,170)
  170 FORMAT(1X)
      DO IR=1,NUMRHOZ
         READ(IOPUREZ,200)
  200    FORMAT(1X)
         READ(IOPUREZ,210)(ZOLAOL(IR,IT),IT=1,NUMTZ)
  210    FORMAT(1P6E12.5)
         END DO
      CLOSE(IOPUREZ)

      RETURN
      END
