C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C SETKRZ
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE SETKRZ(FKUR,FKUR2)
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT LOGICAL*4 (L)
      PARAMETER (NUMT=60)
      PARAMETER (NUMD=50)
      PARAMETER (NUMX=1)
      PARAMETER (NUMXT=NUMT*NUMX)
      PARAMETER (CONST=11604.5D0)
C MHP 8/25 Remove unused variables
      CHARACTER*256 FKUR,FKUR2
C MHP 10/02 missing comma after IDYN
      COMMON/LUNUM/IFIRST, IRUN, ISTAND, IFERMI,
     1    IOPMOD, IOPENV, IOPATM, IDYN,
     2    ILLDAT, ISNU, ISCOMP, IKUR
C      COMMON/LUFNM/ FLAST, FFIRST, FRUN, FSTAND, FFERMI,
C     1    FDEBUG, FTRACK, FSHORT, FMILNE, FMODPT,
C     2    FSTOR, FPMOD, FPENV, FPATM, FDYN,
C     3    FLLDAT, FSNU, FSCOMP, FKUR,
C     4    FMHD1, FMHD2, FMHD3, FMHD4, FMHD5, FMHD6, FMHD7, FMHD8
C GRID ENTRIES FOR TEMPERATURE, AND ABUNDANCE (X)
      COMMON /GKRZ/GRIDT(NUMT)
      COMMON /GKRZ2/GRIDT2(NUMT)
C LOS ALAMOS OPACITY
      COMMON /KRZ/OPACITY(NUMXT,NUMD),RHO(NUMXT,NUMD),NUMTM
      COMMON /KRZ2/OPACITY2(NUMXT,NUMD),RHO2(NUMXT,NUMD),NUMTM2
C OPACITY COMMON BLOCKS - modified 3/09
      COMMON /NEWOPAC/ZLAOL1,ZLAOL2,ZOPAL1,ZOPAL2, ZOPAL951,
     +       ZALEX1, ZKUR1, ZKUR2,TMOLMIN,TMOLMAX,LALEX06,
     +       LLAOL89,LOPAL92,LOPAL95,LKUR90,LALEX95,L2Z
C MHP 8/25 Removed character file names from common block
      COMMON /MISCOPAC/IKUR2,IcondOpacP,LcondOpacP
      SAVE
C
      I=NUMX
    1 FORMAT(2F5.2,5F7.3,3F9.5,F8.3)
C     OPEN TABLE
      OPEN(IKUR,FILE=FKUR, STATUS='OLD')
      READ(IKUR,'(/)')
C
      IPUT=0
      TOUTK=0.0D0
 110  CONTINUE
      READ(IKUR,1,ERR=110,END=120)TOUT,PRES,OKURU0,OKURU1,
     +     OKURU2, OKURU4,OKURU8,DENNE,DENNA,DENS,DUMM
      IF(TOUTK.NE.TOUT)THEN
         IPUT=IPUT+1
         IF(IPUT.GT.NUMT)STOP ' KURUCZ INPUT ERROR'
         GRIDT(IPUT)=TOUT
         TOUTK=TOUT
         ID=1
      ENDIF
      IF(IPUT.LT.1)STOP ' KURUCZ INPUT ERROR'
      RHO(IPUT,ID)=DENS
      OPACITY(IPUT,ID)=10.0D0**OKURU0
      ID=ID+1
      GOTO 110
C
 120  CONTINUE
      NUMTM=IPUT
C     CLOSE THE TABLE WE HAVE READ
      CLOSE(IKUR,ERR=99)
C
C
C
C DBG 12/95 read in second Z table if requested
      IF(L2Z) THEN
C     OPEN TABLE
         OPEN(IKUR2,FILE=FKUR2, STATUS='OLD')
         READ(IKUR2,'(/)')
C
         IPUT=0
         TOUTK=0.0D0
 210     CONTINUE
         READ(IKUR2,1,ERR=210,END=220)TOUT,PRES,OKURU0,OKURU1,
     +        OKURU2, OKURU4,OKURU8,DENNE,DENNA,DENS,DUMM
         IF(TOUTK.NE.TOUT)THEN
            IPUT=IPUT+1
            IF(IPUT.GT.NUMT)STOP ' KURUCZ INPUT ERROR'
            GRIDT2(IPUT)=TOUT
            TOUTK=TOUT
            ID=1
         ENDIF
         IF(IPUT.LT.1)STOP ' KURUCZ INPUT ERROR'
         RHO2(IPUT,ID)=DENS
         OPACITY2(IPUT,ID)=10.0D0**OKURU0
         ID=ID+1
         GOTO 210

 220     CONTINUE
         NUMTM2=IPUT
C CLOSE THE TABLE WE HAVE READ
         CLOSE(IKUR2,ERR=99)
      END IF

      CALL YKOEFF

      RETURN
 99   STOP 'ERROR IN FILE CLOSING'
      END
