C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     SETUPOPAC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE SETUPOPAC(XENV, V,FALEX06,FKUR,FKUR2,FLAOL,FLAOL2,
     *FLIV95,FLLDAT,FOPAL2,FPUREZ,OPECALEX)

      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
      REAL*8 OLAOL,OXA,OT,ORHO,TOLLAOL
C     MHP 8/25 Added pass-through file names
      CHARACTER*256 FALEX06,FKUR,FKUR2,FLAOL,FLAOL2,FLIV95,FLLDAT,
     * FOPAL2,FPUREZ
      CHARACTER*256 OPECALEX(7)
C OPACITY COMMON BLOCKS - modified 3/09
      COMMON /NEWOPAC/ZLAOL1,ZLAOL2,ZOPAL1,ZOPAL2, ZOPAL951,
     +       ZALEX1, ZKUR1, ZKUR2,TMOLMIN,TMOLMAX,LALEX06,
     +       LLAOL89,LOPAL92,LOPAL95,LKUR90,LALEX95,L2Z
C MHP 8/25 Removed character file names from common block
      COMMON/ZRAMP/RSCLZC(50), RSCLZM1(50), RSCLZM2(50),
     *             IOLAOL2, IOOPAL2, NK,
     *             LZRAMP
      COMMON/GRAVS3/FGRY,FGRZ,LTHOUL,LDIFZ
C MHP 8/25 Removed character file names from common block
      COMMON/NWLAOL/OLAOL(12,104,52),OXA(12),OT(52),ORHO(104),TOLLAOL,
     *  IOLAOL, NUMOFXYZ, NUMRHO, NUMT, LLAOL, LPUREZ, IOPUREZ
      DIMENSION V(12)
      SAVE

C
C     THIS SUBROUTINE READS IN SPECIFIED OPACITY TABLES AND
C     SET UP SPLINES FOR THE TABLES.
C     WHEN LZRAMP=T OR LDIFZ=T THEN READ IN SECOND SET OF
C     OPACITY TABLES AT DIFFERENT Z (E.G. ZOPAL952).
      L2Z = LZRAMP.OR.LDIFZ
C
C     INTERIOR TABLES
C
C     READ IN OPAL95 TABLES
      IF (LOPAL95) THEN
        CALL LL95TBL(FLIV95)
      CALL OP95XTAB(XENV)
      END IF

C     READ IN OPAL92 TABLES AT ZOPAL1 AND ZOPAL2
      IF (LOPAL92) THEN
         CALL SETLLO(FLLDAT,FOPAL2)
       CALL LL4TH(XENV)
      END IF
C     READ IN LAOL89 TABLES AT ZLAOL1 AND ZLAOL2
      IF (LLAOL89) THEN
         CALL RDLAOL(V,FLAOL,FLAOL2)
       CALL SULAOL
      END IF
C
C     READ IN LAOL89 PURE Z TABLE
C
      IF(LPUREZ)THEN
         CALL RDZLAOL(FPUREZ)
       CALL ZSULAOL
      END IF
C
C     LOW TEMP TABLES
C
C     READ IN ALEX 2006 TABLES
      IF (LALEX06) THEN
        CALL READALEX06(FALEX06)
C     READ IN ALEX 1995 TABLES
      ELSE IF (LALEX95) THEN
        CALL ALXTBL(OPECALEX)
      CALL ALX8TH(XENV)
C     READ IN KURUCZ TABLE AT ZKUR1 AND ZKUR2
      ELSE IF (LKUR90) THEN
          CALL SETKRZ(FKUR,FKUR2)
      END IF
      RETURN
      END
