C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C SUBROUTINE SPLINTD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C REAL*8 VERSION
C TAKEN FROM NUMERICAL RECIPES, PRESS, ET AL, P89.
C GIVEN THE ARRAYS XA AND YA OF LENGTH N, WHICH TABULATE A FUNCTION
C (WITH THE XA[I]'S IN ORDER), AND GIVEN THE ARRAY Y2A, WHICH IS THE
C OUTPUT OF SPLINE ABOVE, AND GIVEN A VALUE OF X, THIS ROUTINE RETURNS
C A CUBIC-SPLINE INTERPOLATED VALUE Y.
      SUBROUTINE SPLINTD2(XA, YA, N, Y2A, X, Y, KLO, KHI)
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
      PARAMETER (JSON=5000)
      COMMON/LUOUT/ILAST,IDEBUG,ITRACK,ISHORT,IMILNE,IMODPT,ISTOR,IOWR
      DIMENSION XA(JSON), YA(JSON), Y2A(JSON)
      SAVE
      KLO = 1
      KHI = N
    1 IF (KHI-KLO .GT. 1) THEN
         K = (KHI+KLO)/2
         IF (XA(K) .GT. X) THEN
            KHI = K
         ELSE
            KLO = K
         END IF
         GOTO 1
      END IF
      H = XA(KHI) - XA(KLO)
      IF (H .EQ. 0D0) THEN
           WRITE(ISHORT,*) 'ERROR IN SPLINT ROUTINE.'
         STOP
      ENDIF
      A = (XA(KHI)-X)/H
      B = (X - XA(KLO))/H
      Y = A*YA(KLO)+B*YA(KHI)+
     1    ((A**3-A)*Y2A(KLO)+(B**3-B)*Y2A(KHI))*(H**2)/6D0
      RETURN
      END
