C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     SURFOPAC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE SURFOPAC(XENV)
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
C OPACITY COMMON BLOCKS - modified 3/09
      COMMON /NEWOPAC/ZLAOL1,ZLAOL2,ZOPAL1,ZOPAL2, ZOPAL951,
     +       ZALEX1, ZKUR1, ZKUR2,TMOLMIN,TMOLMAX,LALEX06,
     +       LLAOL89,LOPAL92,LOPAL95,LKUR90,LALEX95,L2Z
      SAVE

C     THIS SUBROUTINE SETS UP SURF OPACITY TABLES
C     ASSUMES TABLES HAVE ALREADY BEEN READ IN

C     INTERIOR TABLES

C     SETUP OPAL95 TABLES
      IF (LOPAL95) THEN
      CALL OP95XTAB(XENV)
      END IF
C     SETUP IN OPAL92 TABLES AT ZOPAL1 AND ZOPAL2
      IF (LOPAL92) THEN
        CALL LL4TH(XENV)
      END IF

C     LOW TEMP TABLES

C     INTERPOLATE ALEX95 TABLES
      IF (LALEX95) THEN
       CALL ALX8TH(XENV)
      END IF


      RETURN
      END
