C $$$$$$
      SUBROUTINE WCZIMP(HD,HJM,HR,HS,HS2,ISTART,IEND,ETA2,HI,OMEGA,
     *               QIW,R0,M)

      PARAMETER(JSON=5000)
      IMPLICIT REAL*8(A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
      COMMON/SBROT/LSOLID,IMPJMOD
      COMMON/CONST1/ CLN,CLNI,C4PI,C4PIL,C4PI3L,CC13,CC23,CPI
      COMMON/ROT/WNEW,WALPCZ,ACFPFT,ITFP1,ITFP2,LROT,LINSTB,LWNEW
      DIMENSION HD(JSON),HJM(JSON),HR(JSON),HS(JSON),HS2(JSON),
     *  ETA2(JSON),HI(JSON),OMEGA(JSON),QIW(JSON),R0(JSON)
      SAVE

C JNT 2025/09/03 copy of 2025/05/14 TO MAKE THE CODE ENFORCE
C SPECIFIC ROTATION PROFILES

C JNT 2025/09/03 COPY OF 2015/05/07 ADD IEND.LT.M TO ENFORCE SB
C ROTATION IN CONVECTIVE ZONES THAT ARE NOT THE SURFACE CONVECTIVE
C ZONE EVEN IF WALPCZ IS TURNED ON (I.E. WALPCZ NOW ONLY AFFECTS
C SURFACE CONVECTION ZONES)

      IF((WALPCZ.GE.0.0D0) .OR. (LSOLID) .OR. (IMPJMOD.EQ.1) .OR. (IEND.LT.M)) THEN
C  SOLID BODY ROTATION IN CONVECTIVE REGIONS.
         CALL SOLID(HD,HJM,HR,HS,HS2,ISTART,IEND,ETA2,HI,OMEGA,
     *              QIW,R0,M)     
C JNT 2025/09/03 COPY OF 2015/05/14 ADD OPTION TO MAKE EVERYTHING
C BELOW THE SURFACE CONVECTION ZONE ROTATE AS A SOLID BODY, 
C DETACHED FROM WHAT IS HAPPENING IN THE CONVECTION ZONE
      ELSE IF(IMPJMOD.EQ.2)THEN
         CJTOT = HJM(ISTART)*HS2(ISTART)
         CMTOT = DEXP(CLN*WALPCZ*HR(ISTART))*HI(ISTART)
         DO 30 J = ISTART+1,IEND
            CJTOT = CJTOT + HJM(J)*HS2(J)
            CMTOT = CMTOT + DEXP(CLN*WALPCZ*HR(J))*HI(J)
   30    CONTINUE      
 
C  ASSIGN NEW RUN OF J/M IN THE C.Z. AND FIND THE NEW RUN OF OMEGA.
         W0 = CJTOT/CMTOT
         DO 31 J = ISTART,IEND
            OMEGA(J) = W0*DEXP(CLN*WALPCZ*HR(J))
            HJM(J) = OMEGA(J)*HI(J)/HS2(J)
            JSTART = J
            JEND = J
            CALL SOLID(HD,HJM,HR,HS,HS2,JSTART,JEND,ETA2,HI,
     *                 OMEGA,QIW,R0,M)
   31    CONTINUE
         IF (ISTART.GT.1) THEN
            CALL SOLID(HD,HJM,HR,HS,HS2,1,ISTART-1,ETA2,HI,
     *                 OMEGA,QIW,R0,M)
         ENDIF
C JNT 2025/09/04 REPLICATING 2015/05/14 ADD OPTION TO MAKE 
C EVERYTHING BELOW THE SURFACE CONVECTION ZONE ROTATE AS A
C SOLID BODY AT THE RATE OF THE BASE OF THE CONVECTION ZONE.
      ELSE IF(IMPJMOD.EQ.3) THEN
         CJTOT = HJM(1)*HS2(1)
         CMTOT = DEXP(CLN*WALPCZ*HR(ISTART))*HI(1)
         IF (ISTART.GT.1) THEN
            DO 32 J = 2,ISTART
               CJTOT = CJTOT + HJM(J)*HS2(J)
               CMTOT = CMTOT + DEXP(CLN*WALPCZ*HR(ISTART))*HI(J)
   32       CONTINUE
         ENDIF
         DO 33 J = (ISTART+1),IEND
            CJTOT = CJTOT + HJM(J)*HS2(J)
            CMTOT = CMTOT + DEXP(CLN*WALPCZ*HR(J))*HI(J)
   33    CONTINUE
C  ASSIGN NEW RUN OF J/M IN THE C.Z. AND FIND THE NEW RUN OF OMEGA.

         W0 = CJTOT/CMTOT
         DO 34 J = ISTART,IEND
            OMEGA(J) = W0*DEXP(CLN*WALPCZ*HR(J))
            HJM(J) = OMEGA(J)*HI(J)/HS2(J) 
            JSTART = J
            JEND = J
            CALL SOLID(HD,HJM,HR,HS,HS2,JSTART,JEND,ETA2,HI,
     *                 OMEGA,QIW,R0,M)
   34    CONTINUE         
         IF (ISTART.GT.1) THEN
            DO 35 J = 1,(ISTART-1)
               OMEGA(J) = OMEGA(ISTART)
               HJM(J) = OMEGA(J)*HI(J)/HS2(J) 
   35       CONTINUE   
            CALL SOLID(HD,HJM,HR,HS,HS2,1,ISTART-1,ETA2,HI,
     *                 OMEGA,QIW,R0,M)
         ENDIF              
        
         
      
      ELSE IF((WALPCZ.LE.-2.0D0) .AND. (IMPJMOD.EQ.0))THEN
C  CONSTANT SPECIFIC ANGULAR MOMENTUM PER UNIT MASS IN THE C.Z.
C  FIND TOTAL MASS AND ANGULAR MOMENTUM OF C.Z.
         CJTOT = HJM(ISTART)*HS2(ISTART)
         CMTOT = HS2(ISTART)
         DO 36 J = ISTART+1,IEND
            CJTOT = CJTOT + HJM(J)*HS2(J)
            CMTOT = CMTOT + HS2(J)
   36    CONTINUE
C  ASSIGN NEW RUN OF J/M IN THE C.Z. AND FIND THE NEW RUN OF OMEGA.
         CJNEW = CJTOT/CMTOT
         DO 40 J = ISTART,IEND
            HJM(J) = CJNEW
            OMEGA(J) = CJNEW*HS2(J)/HI(J)
            JSTART = J
            JEND = J
            CALL SOLID(HD,HJM,HR,HS,HS2,JSTART,JEND,ETA2,HI,
     *                 OMEGA,QIW,R0,M)
   40    CONTINUE
      ELSE
C  GENERAL LAW FOR OMEGA IN C.Z.: OMEGA = C*R**WALPCZ,WHERE C IS A CONSTANT
C  FOR THE ENTIRE C.Z. IF THIS HOLDS, THE RUN OF J/M CAN BE FOUND BY
C  SOLVING FOR THE CONSTANT BY REQUIRING THAT THE TOTAL J OF THE C.Z. BE
C  CONSERVED AND THEN USING J/M=C*R**WALPCZ*(MOMENT OF INERTIA PER UNIT
C  MASS).
C  FIND TOTAL MASS AND ANGULAR MOMENTUM OF C.Z.
         CJTOT = HJM(ISTART)*HS2(ISTART)
         CMTOT = DEXP(CLN*WALPCZ*HR(ISTART))*HI(ISTART)
         DO 50 J = ISTART+1,IEND
            CJTOT = CJTOT + HJM(J)*HS2(J)
            CMTOT = CMTOT + DEXP(CLN*WALPCZ*HR(J))*HI(J)
   50    CONTINUE
C  ASSIGN NEW RUN OF J/M IN THE C.Z. AND FIND THE NEW RUN OF OMEGA.
         W0 = CJTOT/CMTOT
         DO 60 J = ISTART,IEND
            OMEGA(J) = W0*DEXP(CLN*WALPCZ*HR(J))
            HJM(J) = OMEGA(J)*HI(J)/HS2(J)
            JSTART = J
            JEND = J
            CALL SOLID(HD,HJM,HR,HS,HS2,JSTART,JEND,ETA2,HI,
     *                 OMEGA,QIW,R0,M)
   60    CONTINUE
      ENDIF
      RETURN
      END
