




C
C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
C WRTMIL
C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
      SUBROUTINE WRTMIL(HCOMP,HD,HL,HP,HR,HS1,M,MODEL)
      PARAMETER (JSON=5000)
      IMPLICIT REAL*8(A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
C MHP 8/25 Milne output file is now opened in parmin,unused variables removed
      COMMON/LUOUT/ILAST,IDEBUG,ITRACK,ISHORT,IMILNE,IMODPT,ISTOR,IOWR
      COMMON/CCOUT1/NPENV,NPRTMOD,NPRTPT,NPOINT
      COMMON/COMP/XENV,ZENV,ZENVM,AMUENV,FXENV(12),XNEW,ZNEW,STOTAL,
     *     SENV
      COMMON/CONST/CLSUN,CLSUNL,CLNSUN,CMSUN,CMSUNL,CRSUN,CRSUNL,CMBOL
      COMMON/CONST1/ CLN,CLNI,C4PI,C4PIL,C4PI3L,CC13,CC23,CPI
      COMMON/CONST2/CGAS,CA3,CA3L,CSIG,CSIGL,CGL,CMKH,CMKHN
      COMMON/SCRTCH/SESUM(JSON),SEG(7,JSON),SBETA(JSON),SETA(JSON),
     * LOCONS(JSON),SO(JSON),SDEL(3,JSON),SFXION(3,JSON),SVEL(JSON),SCP(JSON)
      DIMENSION HCOMP(15,JSON),HD(JSON),HL(JSON),HP(JSON),HR(JSON),
     *     HS1(JSON)
      REAL*8 NP1
      SAVE

C  FIND THE MILNE INVARIANTS U AND V, ALONG WITH THE INDEX N+1.
C  WRITE THEM OUT TO LOGICAL UNIT IMILNE.
C  HEADER
      SMTOT = DEXP(CLN*STOTAL)/CMSUN
      WRITE(IMILNE,5) MODEL,XENV,ZENV,SMTOT
    5 FORMAT(10X,'MODEL',I5,'  XENV =',1PD10.3,'  ZENV =',D10.3,
     *      '  MASS(SOLAR UNITS) =',D10.3)
C  CALCULATE FOR FIRST POINT(ALWAYS DONE)
      D = DEXP(CLN*HD(1))
      P = DEXP(CLN*HP(1))
      R = DEXP(CLN*HR(1))
      U = C4PI*D*R**3/HS1(1)
      V = DEXP(CLN*CGL)*HS1(1)*D/(P*R)
      W = U*HS1(1)*(SESUM(1)+SEG(7,1))/(HL(1)*CLSUN)
      NP1 = 1.0D0/SDEL(2,1)
      WRITE(IMILNE,10)1,HS1(1),R,P,D,HCOMP(1,1),HL(1),U,V,W,NP1
   10 FORMAT(1X,I4,10(1PE11.3))
C  PRINT OUT EVERY NPRTPT POINTS;LAST POINT ALWAYS PRINTED.
      IEND = 1
      IF(NPRTPT.LE.M) THEN
       IBEG = MAX(2,NPRTPT)
       IEND = M - MOD(M,NPRTPT)
       DO 20 I = IBEG,IEND,NPRTPT
          D = DEXP(CLN*HD(I))
          P = DEXP(CLN*HP(I))
          R = DEXP(CLN*HR(I))
          U = C4PI*D*R**3/HS1(I)
          V = DEXP(CLN*CGL)*HS1(I)*D/(P*R)
          W = U*HS1(I)*(SESUM(I)+SEG(7,I))/(HL(I)*CLSUN)
          NP1 = 1.0D0/SDEL(2,I)
          WRITE(IMILNE,10)I,HS1(I),R,P,D,HCOMP(1,I),HL(I),
     *                      U,V,W,NP1
   20    CONTINUE
      ENDIF
      IF(IEND.LT.M) THEN
C  PRINT OUT LAST POINT IF NPRTPT DOESNT DIVIDE EVENLY INTO M.
       D = DEXP(CLN*HD(M))
       P = DEXP(CLN*HP(M))
       R = DEXP(CLN*HR(M))
       U = C4PI*D*R**3/HS1(M)
       V = DEXP(CLN*CGL)*HS1(M)*D/(P*R)
       W = U*HS1(M)*(SESUM(M)+SEG(7,M))/(HL(M)*CLSUN)
       NP1 = 1.0D0/SDEL(2,M)
       WRITE(IMILNE,10)M,HS1(M),R,P,D,HCOMP(1,M),HL(M),
     *                   U,V,W,NP1
      ENDIF
      CLOSE(IMILNE)
      RETURN
      END
