
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     GET FOUR POINTS IN X ARRAY WHICH SURROUND X
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE XRNG4(JX,NUMX,JX1,JX2)
      save

      IF (JX.LE.2) THEN
         JX1 = 1
         JX2 = 4
      ELSE IF (JX.GE.NUMX-2) THEN
         JX1 = NUMX-3
         JX2 = NUMX
      ELSE
         JX1 = JX - 1
         JX2 = JX + 2
      END IF
      RETURN
      END
