C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
C YTIME
C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
      SUBROUTINE YTIME(EG,HCOMP,HD,HL,HS1,HT,JCORE,M,DELTSY,
     *   HR1,HR2,HR3,HR4,HR5,HR6,HR7,HR8,HR9,HR10,HR11,HR12,HR13,
C      *   HF1,HF2,QDP,QDT,JXBEG)  ! KC 2025-05-31
     *   HF1,HF2,JXBEG)
      IMPLICIT REAL*8(A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
      PARAMETER(JSON=5000)
      COMMON/CTLIM/ATIME(14),TCUT(5),TSCUT,TENV0,TENV1,TENV,TGCUT
      COMMON/CONST/CLSUN,CLSUNL,CLNSUN,CMSUN,CMSUNL,CRSUN,CRSUNL,CMBOL
      COMMON/CONST3/CDELRL,CMIXL,CMIXL2,CMIXL3,CLNDP,CSECYR
      COMMON/CT3/LPTIME
C MHP 10/02 added missing common block
      COMMON/NEWEPS/EALPCA,ENU
      COMMON/FLAG/LEXCOM
      DIMENSION HCOMP(15,JSON),HD(JSON),HL(JSON),HS1(JSON),
     * HT(JSON),EG(6)
      DIMENSION HR1(JSON),HR2(JSON),HR3(JSON),HR4(JSON),HR5(JSON),
     *HR6(JSON),HR7(JSON),HR8(JSON),HR9(JSON),HR10(JSON),HR11(JSON),
     *HR12(JSON),HR13(JSON),HF1(JSON),HF2(JSON)
      SAVE
C  STARS WITH A HELIUM LUMINOSITY HAVE A TIMESTEP LIMIT
C       BASED ON THE TIME REQUIRED TO BURN ATIME(4) OF Y AT THE
C       MAXIMUM IN TEMPERATURE OR THE FRACTION ATIME(5) OF Y AT THIS POINT.
C TEST FOR HELIUM FLASH BURNING; HIGH CENTRAL DENSITY IS TAKEN AS
C A SIGN THAT THE MODEL IS A GIANT UNDERGOING A HE FLASH RATHER THAN
C A HORIZONTAL BRANCH STAR.
C       DATA Q3A,QCA/5.85D17,1.7276D18/
      IF (HD(1).GE.5.0D0) THEN
C     SEARCH FOR TEMPERATURE MAXIMUM
       HTMAX = 0.0D0
       ITMAX = 1
       DO 210 IT = 1,M
          IF (HT(IT).GT.HTMAX) THEN
             ITMAX = IT
             HTMAX = HT(IT)
          ENDIF
  210    CONTINUE
C     CALCULATE HELIUM BURNING RATE AT TMAX
       DL = HD(ITMAX)
       TL = HT(ITMAX)
       X = HCOMP(1,ITMAX)
       Y = HCOMP(2,ITMAX)
       Z = HCOMP(3,ITMAX)
       XHE3 = HCOMP(4,ITMAX)
       XC12 = HCOMP(5,ITMAX)
       XC13 = HCOMP(6,ITMAX)
       XN14 = HCOMP(7,ITMAX)
       XN15 = HCOMP(8,ITMAX)
       XO16 = HCOMP(9,ITMAX)
       XO17 = HCOMP(10,ITMAX)
       XO18 = HCOMP(11,ITMAX)
       IF(LEXCOM) THEN
          XH2 = HCOMP(12,ITMAX)
          XLI6 = HCOMP(13,ITMAX)
          XLI7 = HCOMP(14,ITMAX)
          XBE9 = HCOMP(15,ITMAX)
       ENDIF
       IU = ITMAX
         CALL ENGEB(EGG11,EGG22,EGG33,EGG44,EGG55,QED,QET,SUM1,DL,
C      *        TL,QDT,QDP,X,Y,Z,XHE3,XC12,XC13,XN14,XN15,XO16,XO17,
C      *        XO18,XH2,XLI6,XLI7,XBE9,IU,HR1,HR2,HR3,HR4,HR5,HR6,HR7,  ! KC 2025-05-31
     *        TL,X,Y,XHE3,XC12,XC13,XN14,XO16,
     *        XO18,XH2,IU,HR1,HR2,HR3,HR4,HR5,HR6,HR7,
     *        HR8,HR9,HR10,HR11,HR12,HR13,HF1,HF2)
         E = SUM1
         EG(1) = EGG11
         EG(2) = EGG22
         EG(3) = EGG33
         EG(4) = EGG44
         EG(5) = EGG55
         EG(6) = ENU
         ECA = EALPCA
       IF(EG(5).LT.1.D-22) EG(5) = 1.D-22
       DELTSY=1.0D15/EG(5)
      ELSE
C SET LIMITS ON HE BURNING FOR NON-HELIUM FLASH STARS
       YCORE = 1D0 - HCOMP(3,JCORE)
       IF(YCORE.GE.ATIME(1)) THEN

            DELTSY = MIN(ATIME(4),ATIME(5)*YCORE)
C
          DELTSY = (5.85D17/CLSUN)*DELTSY*(HS1(JCORE)/HL(JCORE))

            ELSE

            DELTSY = (5.85D17/CLSUN)*DELTSY*(HS1(JXBEG-1)/HL(JXBEG-1))

C
         ENDIF
C
      ENDIF

      RETURN
      END
