#!/bin/bash
################################################################################
#
#  Makemake -- generates a Makefile when put into the subdirectory containing  
#              the Fortran source for the MODEL program.  The names of all *.f 
#              files in the subdirectory end up in the make file.   
#              LLP   3/18/2009
#
#  There are two auxilliary files:
#  File "BegMake" containsthe part of the makefile that comes before the *.f 
#     files. The purpose of this files is to difine the name of the executable 
#     program. 
#  File "EndMake" contains the part that goes after the *.f files. In this 
#     file the compiler options are set.
#
#  Program "MakeLS" (source in MakeLS.c included) takes a generated Linux 
#     "ls -Cx *.f" file and and punctuates it  properly so that it can be 
#      combined into a proper Makefile.
#
################################################################################

cp MakeBeg Makefile
ls -Cx *.f | ./MakeLS >> Makefile
cat MakeEnd >> Makefile