#!/bin/bash
#
#  MakeModel:  Run make to build version  Model2c
#  This base version is based on Model2b sent to Marc on 4/16/03
#  Included corrections are described above in "ClrListMakeModel"
#  
#  LLP  6/3/03
#
echo ==================================================== >> ListMakeModel
echo Update made on $(date)  >> ListMakeModel
echo >> ListMakeModel
make $1 $2 $3 $4 >> ListMakeModel 2>> ListMakeModel
echo >> ListMakeModel
echo Update Finished at $(date) >> ListMakeModel
echo >> ListMakeModel
