NAME = model4.1.gfort

FFILES = \
alex06tab.f	alfilein.f     alprint.f	 alsurfp.f \
altabinit.f	alx8th.f       alxtbl.f		 alxztab.f \
bandw.f		blkdta000.f    bsrotmix.f	 bsstep.f \
bursmix.f	cases.f        ccoeft.f		 checkc.f \
checkj.f	chkcal.f       chkscal.f	 choose.f \
codiff.f	coefft.f       condopacp.f	 condopacpint.f \
convec.f	cowind.f       crrect.f		 cspline.f \
ctridi.f	dadcoeft.f     dburn.f		 dburnm.f \
dcoeft.f	deutrate.f     engeb.f		 envint.f \
eq2mod.f	eqbound01.f    eqbound06.f	 eqbound.f \
eqburn.f	eqrelv.f       eqsaha.f		 eqscve.f \
eqscvg.f	eqstat2.f      eqstat.f		 equal_to_model.f \
esac01.f	esac06.f       esac.f		 findex.f \
findsh.f	fpft.f	       func.f		 getalex06.f \
getfc.f		getgrid.f      get_imp_diffco.f  getmodel2.f \
getnewenv.f	getopac.f      getopal95.f	 getqua.f \
getrot.f	getw.f	       getyrec7.f	 gmass01.f \
gmass06.f	gmass.f        grsett.f		 gtlaol2.f \
gtlaol.f	gtpurz.f       hpoint.f		 hra.f \
hsolve.f	hsubp.f        htimer.f		 ifermi12.f \
inter3.f	interp.f       intmom.f		 intpol.f \
intpt.f		intrp2.f       kemcom.f		 kspline.f \
ksplint.f	kurucz2.f      kurucz.f		 lax_wendrof1.f \
lax_wendrof2.f	liburn2.f      liburn.f		 lirate88.f \
lir.f		ll4th.f        ll95tbl.f	 locate.f \
lubksb.f	ludcmp.f       main.f		 massloss.f \
mdot.f		meqos.f        meval.f		 mhdpx1.f \
mhdpx2.f	mhdpx.f        mhdst1.f		 mhdst.f \
mhdtbl.f	midmod.f       mixcom.f		 mixcz.f \
mix.f		mixgrid.f      mmid.f		 model_to_equal.f \
momi.f		mu.f	       ndifcom.f	 neutrino.f \
nulosses.f	oeqos01.f      oeqos06.f	 oeqos.f \
op952d.f	op953d.f       op954d.f		 op95xtab.f \
op95ztab.f	osplin.f       oversh.f		 ovrot.f \
parmin.f	pdist.f        physic.f		 pindex.f \
polint.f	ptime.f        putmodel2.f	 putyrec7.f \
qatm.f		qenv.f	       qgauss.f		 quadeos01.f \
quadeos06.f	quad.f	       quint.f		 rabu.f \
radsub01.f	radsub06.f     radsub.f		 rates.f \
ratext.f	rdlaol.f       rdzlaol.f	 readalex06.f \
readcoeos01.f	readcoeos06.f  readco.f		 reduce.f \
rhoofp01.f	rhoofp06.f     rhoofp.f		 rotgrid.f \
rotmix.f	rscale.f       rtab.f		 sconvec.f \
search.f	seculr.f       setcal.f		 setkrz.f \
setllo.f	setscal.f      setscv.f		 setup_grsett.f \
setupopac.f	setups.f       setupv.f		 shape.f \
simeqc.f	slopes.f       sneut.f		 solid.f \
splinc.f	spline.f       splintd2.f	 splint.f \
starin.f	sulaol.f       surfbc.f		 surfopac.f \
surfp.f		t6rinteos01.f  t6rinteos06.f	 t6rinterp.f \
thdiff.f	tpgrad.f       trapzd.f		 tridia.f \
tridiag_gs.f	vcirc.f        viscos.f		 wcz.f \
wind.f		wrthead.f      wrtlst.f		 wrtmil.f \
wrtmod.f	wrtmonte.f     wrtout.f		 wtime.f \
xrng4.f		xtime.f        yalo3d.f		 ykoeff.f \
yllo2d2.f	yllo2d.f       yllo3d2.f	 yllo3d.f \
ylloc.f		ysplin.f       ytime.f		 zero.f \
zfermim12.f	zsulaol.f

FFLAGS =  -c -W -O3 -fno-automatic -ffixed-line-length-132

SRSFILES = $(FFILES)

OBJFILES = $(FFILES:.f=.o)

$(NAME):	$(OBJFILES)
	gfortran -o $(NAME) *.o
	mv $(NAME) /home/llp/bin
.f.o:
	gfortran $(FFLAGS)  $*.f
